name: Deploy PR Preview to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload site
        uses: withastro/action@v3
        with:
          site-url: "https://your-username.github.io/pr-${{ github.event.pull_request.number }}/"

      - name: Deploy preview to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
          url-prefix: "pr-${{ github.event.pull_request.number }}/"

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR preview deployment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.deletePagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
